### ISSUE TITLE
Opening a shulker while standing on it causes glitchy behaviour

### ISSUE THREAD

**Issue by feliscatusmeows** [zeroBzeroT/issues-and-suggestions#15]
If you stand on a shulker box and try to open that shulker box it causes odd behavior and closes the shulker gui after a few moments

**Comment by MaybeEthereas** [comment]
Well thats just minecraft, if you stand on a piston and push it up, you will move up. Same thing

**Comment by nothub** [comment]
yeah, this is a vanilla feature

**Comment by feliscatusmeows** [comment]
Closing the shulker gui when this happens isn't vanilla behavior I'm pretty sure.
