### ISSUE TITLE
All end portals are compromised.

### ISSUE THREAD

**Issue by birsk-was-taken** [zeroBzeroT/issues-and-suggestions#16]
So the problem is that end portal deleting isn't patched.

The old way of doing it was to just place a water bucket on the frame. But now when you do that it just puts the water back in the bucket. But if you break an end portal frame, and then place a block next to the portal block, you can use the water bucket trick on the block instead of the end portal frame.

And at the same time you can't place eyes of ender in end portal frames. So no one can make more portals.

Please fix this.

**Comment by nothub** [comment]
:ok_hand: @Pr3roxDLC is making a nicer patch for that rn that just regenerates portals. gonna be live on test soon
