### ISSUE TITLE
1h slowmode

### ISSUE THREAD

**Issue by autowert66** [zeroBzeroT/issues-and-suggestions#4]
I suggest setting slowmode in #issues-and-suggestions (<#866757355974950972>) to 1 hour.
This would force people to talk in other channels and #issues-and-suggestions would contain less shit

:trollface: 

![😈](https://media.giphy.com/media/sR91D133W02D6/source.gif)

**Comment by nothub** [comment]
yes

**Comment by nothub** [comment]
![](https://scrup.neckbeard.cc/ad615564847f078b49d590a9ca2550cc.png)
:ok_hand:
