### ISSUE TITLE
Add /tphere command

### ISSUE THREAD

**Issue by BajaTests** [zeroBzeroT/issues-and-suggestions#5]
kinda boring asking people to /tpa

**Comment by BajaTests2** [comment]
brilliant idea!

**Comment by nothub** [comment]
no sorry but this is not possible by design.
the related project can be found here: [nothub/SafeTP](https://github.com/nothub/SafeTP)

**Comment by nothub** [comment]
> 20:15] hub: hm idk xD the whole point about safetp is that its not possible to fuck up when your stupid with your keyboard
