### ISSUE TITLE
fix kick on movement

### ISSUE THREAD

**Issue by lifeofacookie** [zeroBzeroT/issues-and-suggestions#6]
Fix the kick plugin I can’t even jump on vanilla with elytra without getting kicked

**Comment by BajaTests** [comment]
just don't use vanilla u nub

**Comment by lifeofacookie** [comment]
It kicks for clients aswell

**Comment by Krazzzzymonkey** [comment]
what does it kick you for?

**Comment by lifeofacookie** [comment]
Kicked for flying

**Comment by lifeofacookie** [comment]
Go into the 0b chat bridge and type kicked for flying they is 6 pages of people saying the same thing

**Comment by nothub** [comment]
this seems to be a thing on main but not happening on test

**Comment by BajaTests** [comment]
u 2 bad to fly

**Comment by autowert66** [comment]
> u 2 bad to fly

If it happens in vanilla client its an server issue

**Comment by BajaTests** [comment]
> If it happens in vanilla client its an server issue
no u

**Comment by nothub** [comment]
it probably is magnified with bad ping

**Comment by lifeofacookie** [comment]
30 ping isn’t bad....

**Comment by BajaTests** [comment]
> Fix the kick plugin I can’t even jump on vanilla with elytra without getting kicked

antarctic ping

**Comment by nothub** [comment]
> 30 ping isn’t bad....

yeah, that is a decent connection that should be fine to play with

**Comment by nothub** [comment]
This is fixed on new version, hop on `test.0b0t.org` to confirm its not too restrictive. Otherwise reopen this ticket.
