### ISSUE TITLE
restrictive limit for book in shulkers

### ISSUE THREAD

**Issue by lifeofacookie** [zeroBzeroT/issues-and-suggestions#7]
Let us have more then 3 different signed books in a shulker

**Comment by nothub** [comment]
indeed, this is a strange artifact of old patches, i am in the process of merging all these book and inventory checks to a central place.

**Comment by nothub** [comment]
Fixed on new version, @lifeofacookie can you test on `test.0b0t.org` to confirm thats what you were actually talking about?

**Comment by nothub** [comment]
Please reopen if the problem persist on test.
